/* eslint-disable no-unused-vars */
import React, { useEffect, useRef, useState, useCallback, useMemo } from "react";
import { createPortal } from "react-dom";
import {
  ShoppingBasket,
  Heart,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Tag,
  ArrowRight,
  Minus,
  ReceiptText,
  Star,
  X,
  Plus,
  Search,
  Store,
  Truck,
  MapPin,
  ShieldCheck,
  UserRound,
  ImagePlus,
  Camera,
  CircleCheck,
  PencilLine,
  LogOut,
  Menu,
  ThumbsUp,
  HandHeart,
  Sparkles,
  Mail,
  Clock,
  MessageCircle,
  Send,
  HelpCircle,
  BookOpen,
  CalendarDays,
  User,
} from "lucide-react";
import { styles, FONT_DISPLAY } from "../../../styles.js";
import { GlobalStyle } from "../../../components/GlobalStyle.jsx";
import { ConfirmDialog } from "../../../components/ConfirmDialog.jsx";
import LocationPickerMap from "../../../components/LocationPickerMap.jsx";
import {
  createMyAddress,
  createCheckout,
  createPayment,
  createReview,
  deleteMyAddress,
  extractOrderId,
  fetchCurrentUserProfile,
  fetchMyAddresses,
  fetchMyOrder,
  fetchMyOrders,
  fetchProductCategories,
  fetchProductDetail,
  fetchProductRating,
  fetchProductReviews,
  fetchSearchEverything,
  fetchSellerStore,
  fetchStoreDetail,
  fetchStoreProducts,
  fetchStoreReviews,
  fetchUserDashboard,
  fetchVouchers,
  followStore,
  registerSeller,
  resolveApiUrl,
  unfollowStore,
  updateCurrentUserProfile,
  updateMyAddress,
} from "../../../lib/userApi.js";
import { getMidtransSnapEnvironment, loadMidtransSnap, resetMidtransSnap } from "../../../lib/midtrans.js";
import {
  getStoredAuthUser,
  getSessionUser,
} from "../../../lib/authApi.js";
import {
  WISHLIST_ACCENTS,
  TRENDING_SEARCHES,
  parseRupiah,
  formatRupiah,
  FOOTER_COLS,
  PRODUCT_FOOTER_CATEGORIES,
  SHIPPING_OPTIONS,
  pickVoucherNumber,
  formatVoucherDate,
  formatDiscountPercent,
  sortAvailableVouchers,
  normalizeAvailableVouchers,
  Reveal,
} from "../../appHelpers.jsx";

const PRODUCT_BG_COLORS = ["#9fd4d9", "#f0c93b", "#bcdff5", "#f2cf4a"];
const PRODUCT_DETAIL_PLACEHOLDER =
  "https://images.unsplash.com/photo-1615529182904-14819c35db37?q=80&w=1100&auto=format&fit=crop";
const STORE_BANNER_PLACEHOLDER =
  "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?q=80&w=1600&auto=format&fit=crop";
const STORE_AVATAR_PLACEHOLDER =
  "https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=420&auto=format&fit=crop";
const PRODUCT_DETAIL_ACCENTS = ["#c53b73", "#f0cc43", "#30a6d6", "#f875b0"];

const productDetailStyles = {
  main: {
    background: "#fdeee2",
    minHeight: "calc(100vh - var(--header-h))",
    overflow: "hidden",
  },
  inner: {
    maxWidth: 1536,
    margin: "0 auto",
    padding: "76px clamp(28px, 5.5vw, 86px) 0",
  },
  backButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    border: "none",
    background: "transparent",
    color: "#b72d64",
    fontSize: 23,
    fontWeight: 800,
    padding: "0 0 118px",
  },
  heroGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(360px, 0.92fr) minmax(420px, 1fr)",
    gap: "84px",
    alignItems: "start",
  },
  galleryCol: {
    minWidth: 0,
  },
  imageFrame: {
    width: "100%",
    aspectRatio: "1 / 1",
    borderRadius: 31,
    border: "5px solid #fff9ec",
    background: "#e8d0b8",
    overflow: "hidden",
    boxShadow: "0 14px 20px -14px rgba(47, 30, 26, 0.42)",
  },
  mainImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  thumbRow: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
    marginTop: 28,
  },
  thumb: {
    width: 80,
    height: 80,
    borderRadius: 11,
    border: "2.5px solid #e8bed1",
    background: "#fff8f2",
    overflow: "hidden",
    padding: 0,
  },
  thumbActive: {
    borderColor: "#c53b73",
    boxShadow: "0 6px 14px -11px rgba(197, 59, 115, 0.72)",
  },
  thumbImage: {
    width: "100%",
    height: "100%",
    display: "block",
    objectFit: "cover",
  },
  sellerCard: {
    display: "grid",
    gridTemplateColumns: "76px auto",
    alignItems: "center",
    gap: 18,
    width: "min(390px, 100%)",
    marginTop: 92,
    border: "none",
    background: "transparent",
    padding: 0,
    textAlign: "left",
    fontFamily: "inherit",
    cursor: "pointer",
  },
  sellerAvatar: {
    width: 76,
    height: 76,
    borderRadius: "50%",
    border: "4px solid #2f1e1a",
    background: "#fff8f2",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    color: "#b72d64",
  },
  sellerAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  sellerNameBox: {
    minHeight: 72,
    borderRadius: 8,
    border: "2px solid #2f1e1a",
    background: "rgba(255, 248, 242, 0.52)",
    color: "#211714",
    display: "flex",
    alignItems: "center",
    padding: "0 20px",
    fontSize: 18,
    fontWeight: 900,
    boxShadow: "0 1px 0 rgba(47, 30, 26, 0.08)",
  },
  sellerMeta: {
    gridColumn: "2",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginTop: -6,
    color: "#67534d",
    fontSize: 15,
  },
  sellerBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    minHeight: 26,
    borderRadius: 999,
    border: "1.5px solid #2f1e1a",
    background: "#ffe885",
    color: "#3a2a07",
    padding: "0 11px",
    fontSize: 13,
    fontWeight: 800,
  },
  detailsCol: {
    minWidth: 0,
    paddingTop: 5,
  },
  title: {
    margin: "0 0 18px",
    color: "#b72d64",
    fontSize: "clamp(38px, 4.2vw, 56px)",
    lineHeight: 1.05,
    fontWeight: 900,
    letterSpacing: 0,
  },
  price: {
    color: "#cfaa00",
    fontSize: 30,
    lineHeight: 1.1,
    fontWeight: 900,
    marginBottom: 26,
  },
  description: {
    color: "#2f1e1a",
    fontSize: 18,
    lineHeight: 1.55,
    maxWidth: 705,
    margin: "0 0 26px",
  },
  chips: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    marginBottom: 32,
  },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 34,
    borderRadius: 999,
    background: "#fff8e8",
    padding: "0 15px",
    fontSize: 14,
    fontWeight: 800,
    transform: "rotate(-2deg)",
  },
  actionRow: {
    display: "grid",
    gridTemplateColumns: "156px minmax(260px, 1fr)",
    gap: 28,
    alignItems: "center",
    marginBottom: 50,
  },
  qtyControl: {
    height: 48,
    borderRadius: 9,
    border: "2px solid #c53b73",
    background: "#fff8e8",
    color: "#8f214d",
    display: "grid",
    gridTemplateColumns: "42px 1fr 42px",
    alignItems: "center",
    overflow: "hidden",
  },
  qtyButton: {
    height: "100%",
    border: "none",
    background: "transparent",
    color: "#c53b73",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  qtyValue: {
    color: "#2f1e1a",
    textAlign: "center",
    fontSize: 20,
    fontWeight: 700,
  },
  addButton: {
    minHeight: 64,
    borderRadius: 999,
    border: "2px solid rgba(255, 248, 236, 0.54)",
    background: "linear-gradient(180deg, #bd2f68 0%, #ad285c 100%)",
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    fontSize: 14,
    fontWeight: 900,
    padding: "0 28px",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.2), 0 12px 24px -18px rgba(168,42,89,0.8)",
  },
  accordion: {
    borderTop: "1.5px solid #e8c4c9",
  },
  accordionItem: {
    borderBottom: "1.5px solid #e8c4c9",
  },
  accordionButton: {
    width: "100%",
    minHeight: 84,
    border: "none",
    background: "transparent",
    color: "#231816",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: 0,
    textAlign: "left",
    fontSize: 17,
    fontWeight: 900,
  },
  accordionBody: {
    color: "#6f5850",
    fontSize: 14.5,
    lineHeight: 1.6,
    padding: "0 0 22px",
  },
  specList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    margin: 0,
  },
  specRow: {
    display: "grid",
    gridTemplateColumns: "minmax(120px, 200px) 1fr",
    gap: 12,
    alignItems: "baseline",
  },
  specName: {
    margin: 0,
    fontWeight: 800,
    color: "#231816",
    fontSize: 14,
  },
  specValue: {
    margin: 0,
    color: "#6f5850",
  },
  careList: {
    margin: 0,
    paddingLeft: 20,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  careItem: {
    color: "#6f5850",
  },
  wave: {
    display: "block",
    width: "100%",
    height: 92,
    margin: "72px 0 58px",
    fill: "none",
    stroke: "rgba(183, 45, 100, 0.42)",
    strokeWidth: 6,
    strokeDasharray: "30 18",
  },
  moreSection: {
    padding: "0 clamp(28px, 5.5vw, 86px) 94px",
  },
  moreTitle: {
    color: "#b72d64",
    textAlign: "center",
    fontSize: "clamp(36px, 4.2vw, 54px)",
    lineHeight: 1.1,
    fontWeight: 900,
    letterSpacing: 0,
    margin: "0 0 62px",
  },
  moreGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "54px 42px",
  },
  moreCard: {
    minWidth: 0,
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  moreImageButton: {
    width: "100%",
    aspectRatio: "1.08 / 1",
    borderRadius: 26,
    border: "3px solid #c53b73",
    background: "#fff8f2",
    padding: 0,
    overflow: "hidden",
    marginBottom: 29,
    position: "relative",
  },
  moreImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  moreTitleText: {
    color: "#2f1e1a",
    fontSize: 25,
    lineHeight: 1.2,
    fontWeight: 500,
    margin: "0 0 8px",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  morePrice: {
    color: "#6f5850",
    fontSize: 16,
    margin: "0 0 20px",
  },
  moreAdd: {
    minWidth: 132,
    minHeight: 44,
    borderRadius: 999,
    border: "none",
    background: "linear-gradient(180deg, #bd2f68 0%, #a82a59 100%)",
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    fontSize: 15,
    fontWeight: 650,
    padding: "0 20px",
  },
stateBox: {
    minHeight: 320,
    border: "1.5px dashed rgba(168, 42, 89, 0.24)",
    borderRadius: 12,
    background: "rgba(255,255,255,0.46)",
    color: "#8a5268",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: 28,
    fontSize: 15,
    fontWeight: 800,
  },
  reviewsSection: {
    position: "relative",
    maxWidth: 1536,
    margin: "0 auto",
    padding: "18px clamp(28px, 5.5vw, 86px) 78px",
  },
  reviewsWave: {
    display: "block",
    width: "100%",
    height: 72,
    fill: "none",
    stroke: "rgba(183, 45, 100, 0.44)",
    strokeWidth: 6,
    strokeDasharray: "31 19",
    strokeLinecap: "butt",
    pointerEvents: "none",
  },
  reviewsWaveBottom: {
    margin: "58px 0 0",
  },
  reviewsHeader: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 20,
    flexWrap: "wrap",
    marginBottom: 28,
  },
  reviewsEyebrow: {
    margin: 0,
    color: "#201715",
    fontFamily: FONT_DISPLAY,
    fontSize: 32,
    lineHeight: 1.15,
    fontWeight: 800,
  },
  reviewsLead: {
    margin: "6px 0 0",
    color: "#6f5850",
    fontSize: 14,
  },
  reviewsSummary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    borderRadius: 999,
    border: "1.5px solid #e8c5d2",
    background: "#fff8f6",
    padding: "8px 16px",
  },
  reviewsAverage: {
    color: "#201715",
    fontSize: 20,
    fontWeight: 900,
    lineHeight: 1,
  },
  reviewsStarsSummary: {
    display: "inline-flex",
    alignItems: "center",
    color: "#f5a623",
  },
  reviewsCount: {
    color: "#6f5850",
    fontSize: 13,
    fontWeight: 700,
  },
  reviewsList: {
    display: "flex",
    flexDirection: "column",
    gap: 24,
    width: "min(720px, 100%)",
    margin: "0 auto",
  },
  reviewsActionRow: {
    display: "flex",
    justifyContent: "center",
    marginTop: 30,
  },
  reviewsAllButton: {
    minHeight: 46,
    borderRadius: 999,
    border: "2px solid #b72d64",
    background: "#fff8f6",
    color: "#b72d64",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "0 20px",
    fontSize: 14,
    fontWeight: 900,
    fontFamily: "inherit",
    boxShadow: "0 10px 18px -16px rgba(168, 42, 89, 0.52)",
    cursor: "pointer",
  },
  reviewItem: {
    position: "relative",
    width: "100%",
    minHeight: 106,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 18,
    alignItems: "center",
    textAlign: "left",
    borderRadius: 22,
    border: "2px solid #ff7fb5",
    background: "#fff8f2",
    color: "#2f1e1a",
    padding: "20px 16px 18px 30px",
    fontFamily: "inherit",
    boxShadow: "0 2px 0 rgba(197, 59, 115, 0.04)",
    cursor: "pointer",
  },
  reviewItemAvatarBox: {
    position: "absolute",
    left: -46,
    top: 0,
    width: 34,
    height: 34,
    borderRadius: "50%",
    overflow: "hidden",
    border: "2px solid #c53b73",
    background: "#ffd7e6",
    color: "#8f214d",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 900,
  },
  reviewItemAvatar: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  reviewItemAvatarFallback: {
    width: "100%",
    height: "100%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  reviewItemBody: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  reviewItemTop: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    flexWrap: "wrap",
  },
  reviewItemName: {
    margin: 0,
    color: "#231816",
    fontSize: 13.5,
    fontWeight: 800,
  },
  reviewItemDate: {
    color: "#9a8078",
    fontSize: 11.5,
    lineHeight: 1,
  },
  reviewItemStars: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    color: "#b72d64",
  },
  reviewItemComment: {
    margin: 0,
    color: "#4c3a35",
    fontSize: 13.5,
    lineHeight: 1.65,
    whiteSpace: "pre-wrap",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  reviewItemPhotoBox: {
    width: 76,
    height: 58,
    borderRadius: 10,
    border: "2px solid #c53b73",
    background: "#f6e8df",
    overflow: "hidden",
    flexShrink: 0,
  },
  reviewItemPhoto: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  reviewsState: {
    borderRadius: 16,
    border: "1.5px dashed #e8c5d2",
    background: "#fff8f6",
    color: "#7b625b",
    padding: "36px 24px",
    textAlign: "center",
    fontSize: 14,
    lineHeight: 1.5,
  },
  reviewsAllOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 500,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    background: "rgba(47, 30, 26, 0.42)",
    backdropFilter: "blur(2px)",
  },
  reviewsAllModal: {
    position: "relative",
    width: "min(860px, 100%)",
    maxHeight: "calc(100vh - 40px)",
    background: "#fff8f2",
    borderRadius: 8,
    border: "2px solid #2f1e1a",
    borderBottom: "8px solid #b72d64",
    boxShadow: "10px 8px 0 rgba(183, 45, 100, 0.78), 0 28px 58px -26px rgba(0, 0, 0, 0.48)",
    padding: "28px clamp(20px, 4vw, 38px) 34px",
    overflowY: "auto",
  },
  reviewsAllHead: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 18,
    marginBottom: 26,
  },
  reviewsAllTitle: {
    margin: 0,
    color: "#201715",
    fontFamily: FONT_DISPLAY,
    fontSize: "clamp(26px, 4vw, 36px)",
    lineHeight: 1.1,
    fontWeight: 800,
  },
  reviewsAllLead: {
    margin: "7px 0 0",
    color: "#6f5850",
    fontSize: 14,
    lineHeight: 1.45,
  },
  reviewsAllClose: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    border: "2px solid #2f1e1a",
    background: "#ffe0eb",
    color: "#2f1e1a",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    cursor: "pointer",
  },
  reviewsAllList: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
    width: "min(720px, calc(100% - 46px))",
    margin: "0 auto",
  },
  reviewDetailOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 520,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    background: "rgba(47, 30, 26, 0.42)",
    backdropFilter: "blur(2px)",
  },
  reviewDetailModal: {
    position: "relative",
    width: "min(820px, 100%)",
    maxHeight: "calc(100vh - 40px)",
    display: "grid",
    gridTemplateColumns: "minmax(260px, 0.92fr) minmax(320px, 1fr)",
    gap: 26,
    background: "#fff8f2",
    borderRadius: 8,
    border: "2px solid #2f1e1a",
    borderBottom: "8px solid #b72d64",
    boxShadow: "10px 8px 0 rgba(183, 45, 100, 0.78), 0 28px 58px -26px rgba(0, 0, 0, 0.48)",
    padding: "22px 28px 24px",
    overflowY: "auto",
  },
  reviewDetailModalNoPhoto: {
    gridTemplateColumns: "minmax(0, 1fr)",
    width: "min(560px, 100%)",
  },
  reviewDetailClose: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 38,
    height: 38,
    borderRadius: "50%",
    border: "2px solid #2f1e1a",
    background: "#ffe985",
    color: "#2f1e1a",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    zIndex: 2,
    cursor: "pointer",
  },
  reviewDetailPhotoFrame: {
    minHeight: 330,
    borderRadius: 12,
    border: "2px solid #2f1e1a",
    background: "#f6e8df",
    overflow: "hidden",
    alignSelf: "stretch",
  },
  reviewDetailPhoto: {
    width: "100%",
    height: "100%",
    minHeight: 330,
    objectFit: "cover",
    display: "block",
  },
  reviewDetailContent: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "12px 0 20px",
  },
  reviewDetailHead: {
    display: "grid",
    gridTemplateColumns: "44px minmax(0, 1fr)",
    gap: 12,
    alignItems: "center",
    paddingRight: 48,
    marginBottom: 12,
  },
  reviewDetailAvatar: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    border: "2px solid #2f1e1a",
    background: "#ffe985",
    color: "#5d4312",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    fontSize: 14,
    fontWeight: 900,
  },
  reviewDetailAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  reviewDetailNameBox: {
    minWidth: 0,
  },
  reviewDetailName: {
    margin: 0,
    color: "#231816",
    fontSize: 23,
    lineHeight: 1.1,
    fontWeight: 900,
  },
  reviewDetailDate: {
    display: "block",
    color: "#6f5850",
    fontSize: 13,
    fontWeight: 700,
    marginTop: 4,
  },
  reviewDetailStars: {
    display: "inline-flex",
    marginBottom: 42,
  },
  reviewDetailQuote: {
    position: "relative",
    margin: "0 0 20px",
    padding: "18px 0 24px 22px",
    color: "#2f1e1a",
    fontSize: 18,
    lineHeight: 1.75,
    borderRight: "4px solid #ffb6d4",
    borderBottom: "4px solid #ffb6d4",
    borderRadius: "0 16px 16px 0",
  },
  reviewDetailHelpful: {
    minHeight: 34,
    borderRadius: 999,
    border: "2px solid #2f1e1a",
    background: "#fff8f2",
    color: "#2f1e1a",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 850,
    padding: "0 18px",
    cursor: "pointer",
  },
};

const storeDetailStyles = {
  main: {
    background: "#fdeee2",
    minHeight: "calc(100vh - var(--header-h))",
    overflow: "hidden",
  },
  inner: {
    maxWidth: 1536,
    margin: "0 auto",
    padding: "74px clamp(28px, 5.5vw, 86px) 112px",
  },
  backButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    border: "none",
    background: "transparent",
    color: "#b72d64",
    fontSize: 18,
    fontWeight: 850,
    padding: "0 0 28px",
  },
  hero: {
    position: "relative",
    minHeight: 384,
    borderRadius: 28,
    border: "3px solid #2d64a1",
    borderTop: "none",
    background: "#cfe1fb",
    overflow: "visible",
    boxShadow: "0 4px 0 #2d64a1",
    marginBottom: 118,
  },
  heroImage: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    opacity: 0.22,
    display: "block",
  },
  heroBlob: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 172,
    height: 214,
    borderBottomLeftRadius: 118,
    background: "#ca79bd",
    opacity: 0.88,
  },
  avatar: {
    position: "absolute",
    left: "clamp(40px, 5vw, 78px)",
    bottom: -68,
    width: 142,
    height: 142,
    borderRadius: "50%",
    border: "5px solid #2f1e1a",
    background: "#fff8f2",
    overflow: "hidden",
    zIndex: 2,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  avatarFallback: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#b72d64",
  },
  identity: {
    position: "absolute",
    left: "clamp(214px, 18vw, 292px)",
    bottom: -55,
    minHeight: 92,
    maxWidth: "min(620px, calc(100% - 430px))",
    borderRadius: 10,
    border: "2.5px solid #2f1e1a",
    background: "rgba(255,248,242,0.88)",
    boxShadow: "0 3px 0 rgba(47,30,26,0.18)",
    padding: "20px 26px 16px",
    zIndex: 2,
  },
  name: {
    margin: "0 0 9px",
    color: "#211714",
    fontSize: "clamp(31px, 3.3vw, 52px)",
    lineHeight: 1.02,
    fontWeight: 950,
    letterSpacing: 0,
  },
  metaRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
    color: "#67534d",
    fontSize: 15,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    minHeight: 28,
    borderRadius: 999,
    border: "1.5px solid #2f1e1a",
    background: "#ffe885",
    color: "#3a2a07",
    padding: "0 12px",
    fontSize: 13,
    fontWeight: 850,
  },
  follow: {
    position: "absolute",
    right: "clamp(38px, 5vw, 84px)",
    bottom: -36,
    minHeight: 52,
    borderRadius: 8,
    border: "2px solid #2f1e1a",
    background: "#ad2d68",
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    fontSize: 15,
    fontWeight: 900,
    padding: "0 28px",
    boxShadow: "5px 5px 0 #8f214d",
    zIndex: 2,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 28,
    marginBottom: 94,
  },
  statCard: {
    minHeight: 148,
    borderRadius: 12,
    border: "2px solid #2f1e1a",
    background: "rgba(255,248,242,0.74)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    boxShadow: "5px 5px 0 #f2ca4c",
  },
  statValue: {
    color: "#211714",
    fontSize: 31,
    lineHeight: 1,
    fontWeight: 950,
  },
  statLabel: {
    color: "#5f4b48",
    fontSize: 12,
    fontWeight: 850,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  storyGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(300px, 420px)",
    gap: 58,
    alignItems: "start",
    marginBottom: 88,
  },
  storyCard: {
    position: "relative",
    borderRadius: 118,
    background: "rgba(255,248,242,0.64)",
    padding: "58px clamp(30px, 4vw, 58px)",
    minHeight: 470,
  },
  storyTitle: {
    margin: "0 0 28px",
    color: "#211714",
    fontSize: 31,
    lineHeight: 1.1,
    fontWeight: 900,
  },
  storyText: {
    color: "#5f4b48",
    fontSize: 17,
    lineHeight: 1.75,
    margin: "0 0 24px",
    whiteSpace: "pre-line",
  },
  tagRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 30,
  },
  tag: {
    minHeight: 34,
    borderRadius: 999,
    border: "1.5px solid #2f1e1a",
    display: "inline-flex",
    alignItems: "center",
    padding: "0 16px",
    fontSize: 12,
    fontWeight: 850,
  },
  rulesCard: {
    position: "relative",
    border: "2px solid #2f1e1a",
    background: "#ffe8b7",
    padding: "44px 32px 34px",
    boxShadow: "8px 8px 0 #f4cf58",
    transform: "rotate(1deg)",
  },
  rulesPin: {
    position: "absolute",
    top: -18,
    left: "50%",
    transform: "translateX(-50%)",
    width: 48,
    height: 48,
    borderRadius: "50%",
    border: "2px solid #2f1e1a",
    background: "#ad2d68",
    color: "#fff8f2",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  rulesTitle: {
    margin: "0 0 22px",
    color: "#211714",
    fontSize: 28,
    lineHeight: 1.1,
    textAlign: "center",
    fontWeight: 900,
  },
  rulesDivider: {
    borderTop: "2px dashed #2f1e1a",
    margin: "0 0 26px",
  },
  ruleItem: {
    display: "grid",
    gridTemplateColumns: "44px minmax(0, 1fr)",
    gap: 16,
    alignItems: "start",
    marginBottom: 24,
  },
  ruleIcon: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    border: "1.5px solid #2f1e1a",
    background: "#fff8f2",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  ruleTitle: {
    display: "block",
    color: "#211714",
    fontSize: 14,
    fontWeight: 900,
    marginBottom: 4,
  },
  ruleText: {
    color: "#5f4b48",
    fontSize: 13,
    lineHeight: 1.45,
    margin: 0,
  },
  productsSection: {
    paddingTop: 6,
  },
  productsTitle: {
    margin: "0 0 32px",
    color: "#b72d64",
    fontSize: "clamp(34px, 4vw, 48px)",
    lineHeight: 1.1,
    textAlign: "center",
    fontWeight: 950,
  },
  productsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "52px 36px",
  },
  stateBox: {
    minHeight: 260,
    border: "1.5px dashed rgba(168, 42, 89, 0.26)",
    borderRadius: 12,
    background: "rgba(255,255,255,0.44)",
    color: "#8a5268",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    padding: 28,
    fontSize: 15,
    fontWeight: 800,
  },
};

export {
  PRODUCT_BG_COLORS,
  PRODUCT_DETAIL_PLACEHOLDER,
  STORE_BANNER_PLACEHOLDER,
  STORE_AVATAR_PLACEHOLDER,
  PRODUCT_DETAIL_ACCENTS,
  productDetailStyles,
  storeDetailStyles
};